name: your-workflow-name
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
        run: npm install -g @dvcorg/cml
      - name: Train model
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install --upgrade pip
          pip3 install -r requirements.txt
          python3 train.py
          cat metrics.txt >> report.md
          echo "![](./plot.png)" >> report.md
          cml comment create report.md
